model_list:
  - model_name: text-embedding-3-small
    litellm_params:
      model: openai/text-embedding-3-small
      api_base: https://opencode.ai/zen/v1
      api_key: os.environ/OPENCODE_ZEN_API_KEY
      mode: embedding
  - model_name: big-pickle
    litellm_params:
      model: openai/big-pickle
      api_base: https://opencode.ai/zen/v1
      api_key: os.environ/OPENCODE_ZEN_API_KEY
      input_cost_per_token: 0.0000005
      output_cost_per_token: 0.0000015

  - model_name: deepseek-v4-flash-free
    litellm_params:
      model: openai/deepseek-v4-flash-free
      api_base: https://opencode.ai/zen/v1
      api_key: os.environ/OPENCODE_ZEN_API_KEY
      input_cost_per_token: 0.0000001
      output_cost_per_token: 0.0000004

  - model_name: mimo-v2.5-free
    litellm_params:
      model: openai/mimo-v2.5-free
      api_base: https://opencode.ai/zen/v1
      api_key: os.environ/OPENCODE_ZEN_API_KEY
      input_cost_per_token: 0.0000001
      output_cost_per_token: 0.0000004

  - model_name: north-mini-code-free
    litellm_params:
      model: openai/north-mini-code-free
      api_base: https://opencode.ai/zen/v1
      api_key: os.environ/OPENCODE_ZEN_API_KEY
      input_cost_per_token: 0.0000001
      output_cost_per_token: 0.0000004

  - model_name: nemotron-3-ultra-free
    litellm_params:
      model: openai/nemotron-3-ultra-free
      api_base: https://opencode.ai/zen/v1
      api_key: os.environ/OPENCODE_ZEN_API_KEY
      input_cost_per_token: 0.0000001
      output_cost_per_token: 0.0000004

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/LITELLM_DATABASE_URL
